def get_team_name(team):
    
    team_lower = team.lower() 

    team_mappings = {
        ## England
        "leicester": "Leicester City",
        "stoke": "Stoke City",
        "swansea": "Swansea City",
        "cardiff": "Cardiff City",
        "norwich": "Norwich City",
        "newcastle": "Newcastle Utd",
        "sheffield": "Sheffield Utd",
        "luton": "Luton Town",
        "ipswich": "Ipswich Town",
        "villa": "Aston Villa",
        "brighton & hove": "Brighton",
        "brighton and hove albion": "Brighton",
        "bha": "Brighton",
        "palace": "Crystal Palace",
        "c. palace": "Crystal Palace",
        "c palace": "Crystal Palace",
        "leeds": "Leeds United",
        "leeds utd": "Leeds United",
        "m city": "Manchester City",
        "man city": "Manchester City",
        "m united": "Manchester Utd",
        "man united": "Manchester Utd",
        "manchester united": "Manchester Utd",
        "man utd": "Manchester Utd",
        "nottingham": "Nott'ham Forest",
        "forest": "Nott'ham Forest",
        "nottingham forest": "Nott'ham Forest",
        "spurs": "Tottenham",
        "wba": "West Brom",
        "west bromwich albion": "West Brom",
        "west bromwich": "West Brom",
        "west ham united": "West Ham",
        "wolverhampton": "Wolves",

        ## Spain
        "alaves": "Alavés",
        "almeria": "Almería",
        "athletic bilbao": "Athletic Club",
        "athletic": "Athletic Club",
        "bilbao": "Athletic Club",
        "atletico": "Atlético Madrid",
        "atletico madrid": "Atlético Madrid",
        "barca": "Barcelona",
        "celta": "Celta Vigo",
        "cadiz": "Cádiz",
        "deportivo": "La Coruña",
        "depor": "La Coruña",
        "deportivo la coruna": "La Coruña",
        "leganes": "Leganés",
        "malaga": "Málaga",
        "rayo": "Rayo Vallecano",
        "vallecano": "Rayo Vallecano",
        "real": "Real Madrid",
        "madrid": "Real Madrid",
        "sociedad": "Real Sociedad",

        ## France
        "clermont": "Clermont Foot",
        "nimes": "Nîmes",
        "psg": "Paris S-G",
        "paris": "Paris S-G",
        "paris saint-germain": "Paris S-G",
        "paris sg": "Paris S-G",
        "st-etienne": "Saint-Étienne",
        "saint-etienne": "Saint-Étienne",

        ## Germany
        "bielefeld": "Arminia",
        "arminia bielefeld": "Arminia",
        "fc bayern": "Bayern Munich",
        "bayern": "Bayern Munich",
        "darmstadt": "Darmstadt 98",
        "fortuna": "Düsseldorf",
        "fortuna dusseldorf": "Düsseldorf",
        "dusseldorf": "Düsseldorf",
        "bvb": "Dortmund",
        "borussia": "Dortmund",
        "borussia dortmund": "Dortmund",
        "eintracht": "Eint Frankfurt",
        "eintracht frankfurt": "Eint Frankfurt",
        "frankfurt": "Eint Frankfurt",
        "borussia monchengladbach": "Gladbach",
        "monchengladbach": "Gladbach",
        "furth": "Greuther Fürth",
        "greuther furth": "Greuther Fürth",
        "hsv": "Hamburger SV",
        "hamburg": "Hamburger SV",
        "hamburg sv": "Hamburger SV",
        "hannover": "Hannover 96",
        "hertha": "Hertha BSC",
        "hertha berlin": "Hertha BSC",
        "kiel": "Holstein Kiel",
        "cologne": "Köln",
        "koln": "Köln",
        "bayer": "Leverkusen",
        "bayer leverkusen": "Leverkusen",
        "mainz": "Mainz 05",
        "nurnberg": "Nürnberg",
        "nuremberg": "Nürnberg",
        "paderborn": "Paderborn 07",
        "sc paderborn": "Paderborn 07",
        "schalke": "Schalke 04",
        "st pauli": "St. Pauli",
        "red bull": "RB Leipzig",
        "leipzig": "RB Leipzig",
        "red bull leipzig": "RB Leipzig",
        "union": "Union Berlin",
        "werder": "Werder Bremen",

        ## Italy
        "verona": "Hellas Verona",
        "internazionale": "Inter",
        "ac milan": "Milan",
        "milano": "Milan",
    }

    return team_mappings.get(team_lower, team.title())
